allowBuilds:
  '@6cdh/tree-sitter-racket': false
  '@6cdh/tree-sitter-scheme': false
  '@eagleoutice/tree-sitter-r': false
  '@elm-tooling/tree-sitter-elm': false
  '@tree-sitter-grammars/tree-sitter-hcl': false
  '@tree-sitter-grammars/tree-sitter-lua': false
  '@tree-sitter-grammars/tree-sitter-markdown': false
  '@tree-sitter-grammars/tree-sitter-toml': false
  '@tree-sitter-grammars/tree-sitter-xml': false
  '@tree-sitter-grammars/tree-sitter-zig': false
  tree-sitter-bash: false
  tree-sitter-c: false
  tree-sitter-c-sharp: false
  tree-sitter-cli: true
  tree-sitter-commonlisp: false
  tree-sitter-cpp: false
  tree-sitter-css: false
  tree-sitter-dart: false
  tree-sitter-elisp: false
  tree-sitter-elixir: false
  tree-sitter-embedded-template: false
  tree-sitter-erlang: false
  tree-sitter-go: false
  tree-sitter-graphql: false
  tree-sitter-haskell: false
  tree-sitter-html: false
  tree-sitter-java: false
  tree-sitter-javascript: false
  tree-sitter-json: false
  tree-sitter-julia: false
  tree-sitter-kotlin: false
  tree-sitter-nix: false
  tree-sitter-objc: false
  tree-sitter-ocaml: false
  tree-sitter-perl: false
  tree-sitter-php: false
  tree-sitter-prisma: false
  tree-sitter-python: false
  tree-sitter-query: false
  tree-sitter-regex: false
  tree-sitter-ruby: false
  tree-sitter-rust: false
  tree-sitter-scala: false
  tree-sitter-scss: false
  tree-sitter-sql: false
  tree-sitter-swift: false
  tree-sitter-typescript: false
  tree-sitter-vimdoc: false
  tree-sitter-vue: false
  tree-sitter-yaml: false
