name: Build and Publish WASMs

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.55

      - name: Install Dependencies
        run: pnpm install

        
      - name: Install WASI SDK
        run: |
          WASI_VERSION=29
          CACHE_DIR="$HOME/.cache/tree-sitter"
          SDK_DIR="$CACHE_DIR/wasi-sdk"

          mkdir -p "$CACHE_DIR"

          if [ ! -d "$SDK_DIR" ]; then
            curl -LO \
              "https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${WASI_VERSION}/wasi-sdk-${WASI_VERSION}.0-x86_64-linux.tar.gz"

            mkdir -p "$SDK_DIR"

            tar -xzf \
              "wasi-sdk-${WASI_VERSION}.0-x86_64-linux.tar.gz" \
              --strip-components=1 \
              -C "$SDK_DIR"
          fi

          echo "$SDK_DIR/bin" >> $GITHUB_PATH
          echo "WASI_SDK_PATH=$SDK_DIR" >> $GITHUB_ENV

      - name: Build WASMs
        run: pnpm run build
        env:
          WASI_SDK_PATH: ${{ github.workspace }}/opt/wasi-sdk

      - name: Publish to NPM
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
